global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#mikhail_shamshurin'
