version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backnet
  ui:
    image: ${USERNAME}/ui:${SERVICES_VERSION}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}/tcp
    networks:
      - frontnet
  post:
    image: ${USERNAME}/post:${SERVICES_VERSION}
    networks:
      - backnet
      - frontnet
  comment:
    image: ${USERNAME}/comment:${SERVICES_VERSION}
    networks:
      - backnet
      - frontnet
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - backnet
      - frontnet

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - backnet
      - frontnet

volumes:
  post_db:
  prometheus_data:

networks:
  backnet:
  frontnet:
